@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjM2NTM0ZWI2MjhjZjlmNjEwMzM2NjciLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTU0ODE3NDYsImV4cCI6MTcxNTU2ODE0Nn0.ppgij_8woGLiSIHcbObRBEdwU_YyVvYIp-vnd-8mi_Y
@tokenCommerce = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQwMmQxNGE5OTkyYmVmZjI3NjA4MTIiLCJpYXQiOjE3MTU0ODE4NzYsImV4cCI6MTcxNTU2ODI3Nn0.0ie0-ZRfGu9ty2JehenC9RNswA-nsAvEa-kD5ne-G6w

### POST register user

POST http://localhost:3000/api/auth/register/user
Content-Type: application/json

{
    "name": "bbb",
    "email": "bbb@test.com",
    "password": "bbb12345",
    "age": 28,
    "city": "Valencia",
    "interests": ["music"],
    "role": "user",
    "avatar": "https://github.com/0SC4R24.png",
    "canReceiveOffers": false
}

### GET all users

GET http://localhost:3000/api/auth/users

### GET user by role

GET http://localhost:3000/api/auth/users?role=user

### GET user by city

GET http://localhost:3000/api/auth/users?city=Valencia

### GET user by offers

GET http://localhost:3000/api/auth/users?offers=false

### GET user by id

GET http://localhost:3000/api/auth/user/6633d48d409f04c8d12a5935

### POST login user

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test24@test.com",
    "password": "test12345"
}

### GET user by id

GET http://localhost:3000/api/auth/user/663d846c57aa4ae84b7a6245

### POST register admin

POST http://localhost:3000/api/auth/register/admin
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "admin12",
    "email": "admin@test.com",
    "password": "admin12345",
    "age": 28,
    "city": "Barcelona",
    "interests": ["sports", "music"],
    "role": "admin",
    "avatar": "https://github.com/0SC4R24.png",
    "canReceiveOffers": false
}

### POST register commerce

POST http://localhost:3000/api/auth/register/commerce
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "email": "comercio@test.com",
    "password": "comercio12345",
    "name": "comercio",
    "description": "comercio de ropa",
    "address": "Valencia",
    "cif": "A12345678",
    "phone": "123456789"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "admin12345"
}

### UPDATE user

PUT http://localhost:3000/api/auth/user/663d846c57aa4ae84b7a6245
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkODQ2YzU3YWE0YWU4NGI3YTYyNDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTU0NjAzMjAsImV4cCI6MTcxNTU0NjcyMH0.SyMfzmqKFzriurZRMjA4Je4cSlB9olJtCKPyTZTF-1A

{
    "name": "admin121",
    "email": "admin1@test.com",
    "password": "admin@12345",
    "age": 29,
    "city": "Toledo",
    "interests": ["music"],
    "role": "admin",
    "avatar": "https://github.com/0SC4R24.png",
    "canReceiveOffers": true
}

### POST log in with new user

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin1@test.com",
    "password": "admin@12345"
}

### DELETE user

DELETE http://localhost:3000/api/auth/user/663d846c57aa4ae84b7a6245
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNkODQ2YzU3YWE0YWU4NGI3YTYyNDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTU0NjAzMjAsImV4cCI6MTcxNTU0NjcyMH0.SyMfzmqKFzriurZRMjA4Je4cSlB9olJtCKPyTZTF-1A

### POST register commerce

POST http://localhost:3000/api/auth/register/commerce
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "email": "info@mercadona.es",
    "password": "mercadona12345",
    "name": "Mercadona",
    "description": "Supermercado",
    "address": "Valencia",
    "cif": "A12345678",
    "phone": "123456789"
}

### POST log in with commerce

POST http://localhost:3000/api/auth/login/commerce
Content-Type: application/json

{
    "email": "info@mercadona.es",
    "password": "mercadona12345"
}


