### POST register user

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "aaa",
    "email": "aaa@test.com",
    "password": "aaa12345",
    "age": 28,
    "city": "Valencia",
    "interests": ["music"],
    "avatar": "https://github.com/0SC4R24.png",
    "role": "user",
    "canReceiveOffers": false
}

### GET all users

GET http://localhost:3000/api/auth/users

### GET user by role

GET http://localhost:3000/api/auth/users?role=admin

### GET user by offers

GET http://localhost:3000/api/auth/users?offers=false

### GET user by id

GET http://localhost:3000/api/auth/users/6633d48d409f04c8d12a5935

### POST login user

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test24@test.com",
    "password": "test12345"
}

### GET user by id

GET http://localhost:3000/api/auth/users/6636534eb628cf9f61033667