### POST register user

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "test24",
    "email": "test24@test.com",
    "password": "test12345",
    "age": 21,
    "city": "Madrid",
    "interests": ["sports", "music"],
    "avatar": "https://github.com/0SC4R24.png",
    "role": "user",
    "canReceiveOffers": true
}

### GET all users

GET http://localhost:3000/api/auth/users

### GET user by role

GET http://localhost:3000/api/auth/users?role=admin

### GET user by id

GET http://localhost:3000/api/auth/users/6633d48d409f04c8d12a5935

### POST login user

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test24@test.com",
    "password": "test12345"
}

###